### ISSUE TITLE
NavigationEvent deprecated

### ISSUE THREAD

**Issue by resign** [skoumalcz/teanity-app#1]
This example uses NavigationEvent which is deprecated. Could you please update the example in order to reflect the recommended practice?

**Comment by diareuse** [comment]
Of course I will, but I don't have enough time to do so right now. Teanity will receive number of QOL updates in near future I hope, so I will focus on updating the example accordingly.

You can refer to [android docs](https://developer.android.com/guide/navigation/) to learn how to use navigation library properly (we used it improperly due to some restrictions, which no longer apply) and [here](https://github.com/skoumalcz/teanity/blob/1.0/core/src/main/java/com/skoumal/teanity/viewmodel/TeanityViewModel.kt#L110) on how to use NavDirections through your ViewModel

**Comment by diareuse** [comment]
Preview has been updated to match the newest snapshot of Teanity in https://github.com/skoumalcz/teanity-app/commit/97207baca924fe9a2146a56cb02acab5642101ad

**Please note that by cloning this example you're no longer using teanity in version 1.0!**

Deprecated members and RxJava have been removed in full extent for the 1.1 onwards. If you depend on it, you still have some time to transition to coroutines.

1.0 is entering LTS and will not receive any new features, only crucial bug fixes.
